name: Update SportTV1 Link

on:
  schedule:
    # */30 significa "a cada 30 minutos"
    - cron: "*/30 * * * *"
  workflow_dispatch: # Mantém isto para poderes testar manualmente sempre que quiseres

jobs:
  update_link:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python extrair_link.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add sporttv1.m3u
          # O commit só acontece se o ficheiro tiver mudado (token novo)
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SportTV1: $(date +'%Y-%m-%d %H:%M')" && git push)
