name: Update SportTV1 Link

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install selenium webdriver-manager requests

      - name: Executar Extração (Selenium)
        run: python extrair_link.py

      - name: Guardar Ficheiro
        run: |
          git config --global user.name "Megatuga Bot"
          git config --global user.email "bot@github.com"
          git add sporttv1.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Link atualizado: $(date +'%H:%M')" && git push)
